version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: adminbrabo
      POSTGRES_PASSWORD: 82094ncjaad214
      POSTGRES_DB: banco_pg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: